apiVersion: v1
kind: ReplicationController
metadata:
  name: demo74
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo74
  template:
    metadata:
      labels:
        app: demo74
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo74
        image: ${docker-registry}/${docker-namespace}/demo74:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080